# 01 · Data Audit
**Goal:** Load all four raw datasets and look at their shape, types, missing values, and basic statistics.

### Load the four raw datasets

In [4]:
import pandas as pd

menu         = pd.read_csv('../data/raw/starbucks_menu.csv')
transactions = pd.read_csv('../data/raw/synthetic_transactions.csv')
macro        = pd.read_csv('../data/raw/fred_macro.csv')
weather      = pd.read_csv('../data/raw/weather_daily.csv')

### Show each datasets' first 5 rows using head()

In [5]:
menu.head()

,product_name,category,size,price_usd,calories,sugar_g,caffeine_mg,seasonal_flag
0,Brewed Coffee,Coffee,Short,2.03,3,0,175.0,1
1,Brewed Coffee,Coffee,Tall,2.18,4,0,260.0,0
2,Brewed Coffee,Coffee,Grande,2.55,5,0,330.0,0
3,Brewed Coffee,Coffee,Venti,2.92,5,0,410.0,0
4,Caffè Latte,Classic Espresso Drinks,Short,3.36,70,9,75.0,0

In [6]:
transactions.head()

,transaction_id,date,hour,time_slot,city,persona,is_weekend,temp_f,cpi,category,product_name,size,base_price,customizations,n_customizations,upcharge,total_price,calories,sugar_g,caffeine_mg
0,TXN-000001,2024-07-12,10,late_morning,Seattle,morning_commuter,0,67.9,314.1,Classic Espresso Drinks,Caffè Latte,Grande,4.21,none,0,0.0,4.99,100,9,75.0
1,TXN-000002,2024-07-09,8,morning_rush,New York,student,0,80.6,314.1,Classic Espresso Drinks,Caffè Latte,Grande,4.21,Whipped Cream,1,0.0,4.99,100,9,75.0
2,TXN-000003,2024-10-07,7,morning_rush,New York,health_conscious,0,65.6,316.5,Classic Espresso Drinks,Vanilla Latte (Or Other Flavoured Latte),Grande,4.21,Whipped Cream,1,0.0,5.03,130,17,75.0
3,TXN-000004,2025-06-29,7,morning_rush,Los Angeles,weekend_explorer,1,72.4,322.2,Classic Espresso Drinks,Caffè Americano,Grande,4.23,none,0,0.0,5.14,15,0,225.0
4,TXN-000005,2024-12-27,6,early_morning,New York,morning_commuter,0,25.1,319.0,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande,5.08,none,0,0.0,6.12,200,38,0.0

In [7]:
macro.head()

         date      cpi  avg_hourly_earnings  real_wage_index
0  2021-03-01  264.961                30.03          11.3337
1  2021-04-01  266.614                30.22          11.3347
2  2021-05-01  268.383                30.41          11.3308
3  2021-06-01  270.654                30.54          11.2838
4  2021-07-01  271.903                30.66          11.2761

In [8]:
weather.head()

         date  temp_mean_f  temp_max_f  temp_min_f      city
0  2024-03-15         58.9        71.0        46.8  New York
1  2024-03-16         48.8        57.8        40.6  New York
2  2024-03-17         51.6        60.4        45.0  New York
3  2024-03-18         44.0        48.6        36.3  New York
4  2024-03-19         38.4        45.5        32.5  New York

### Inspect each dataset's structure using info()

In [9]:
menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   242 non-null    object
 1   category       242 non-null    object
 2   size           242 non-null    object
 3   price_usd      242 non-null    float64
 4   calories       242 non-null    int64
 5   sugar_g        242 non-null    int64
 6   caffeine_mg    219 non-null    float64
 7   seasonal_flag  242 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 15.3+ KB

In [10]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    100000 non-null  object
 1   date              100000 non-null  object
 2   hour              100000 non-null  int64
 3   time_slot         100000 non-null  object
 4   city              100000 non-null  object
 5   persona           100000 non-null  object
 6   is_weekend        100000 non-null  int64
 7   temp_f            100000 non-null  float64
 8   cpi               95676 non-null   float64
 9   category          100000 non-null  object
 10  product_name      100000 non-null  object
 11  size              100000 non-null  object
 12  base_price        100000 non-null  float64
 13  customizations    100000 non-null  object
 14  n_customizations  100000 non-null  int64
 15  upcharge          100000 non-null  float64
 16  total_price       95676 non-null   float64
 17  calories          100000 non-null  int64
 18  sugar_g           100000 non-null  int64
 19  caffeine_mg       91814 non-null   float64
dtypes: float64(6), int64(5), object(9)
memory usage: 15.3+ MB

In [11]:
macro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 60 non-null     object
 1   cpi                  59 non-null     float64
 2   avg_hourly_earnings  60 non-null     float64
 3   real_wage_index      59 non-null     float64
dtypes: float64(3), object(1)
memory usage: 2.0+ KB

In [12]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3655 entries, 0 to 3654
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3655 non-null   object
 1   temp_mean_f  3655 non-null   float64
 2   temp_max_f   3655 non-null   float64
 3   temp_min_f   3655 non-null   float64
 4   city         3655 non-null   object
dtypes: float64(3), object(2)
memory usage: 142.9+ KB

### Describe each dataset's statistics using describe()

In [25]:
menu.describe()

        price_usd    calories     sugar_g  caffeine_mg  seasonal_flag
count  242.000000  242.000000  242.000000   219.000000     242.000000
mean     4.421157  193.871901   32.962810    89.520548       0.078512
std      0.690350  102.863303   19.730199    64.726831       0.269534
min      2.030000    0.000000    0.000000     0.000000       0.000000
25%      3.962500  120.000000   18.000000    50.000000       0.000000
50%      4.365000  185.000000   32.000000    75.000000       0.000000
75%      5.030000  260.000000   43.750000   142.500000       0.000000
max      5.900000  510.000000   84.000000   410.000000       1.000000

In [26]:
transactions.describe()

,hour,is_weekend,temp_f,cpi,base_price,n_customizations,upcharge,total_price,calories,sugar_g,caffeine_mg
count,100000.000000,100000.000000,100000.000000,95676.000000,100000.000000,100000.000000,100000.000000,95676.000000,100000.000000,100000.00000,91814.000000
mean,11.007050,0.285980,57.651672,320.025802,4.305409,0.536910,0.323128,5.590284,155.128770,27.96176,116.175638
std,3.613092,0.451882,16.535721,4.725588,0.891496,0.813218,0.528489,1.260951,102.211695,20.97485,103.054752
min,5.000000,0.000000,-3.200000,313.000000,2.030000,0.000000,0.000000,2.400000,0.000000,0.00000,0.000000
25%,8.000000,0.000000,47.400000,315.600000,3.940000,0.000000,0.000000,4.940000,90.000000,14.00000,70.000000
50%,11.000000,0.000000,60.300000,319.800000,4.330000,0.000000,0.000000,5.670000,150.000000,26.00000,75.000000
75%,14.000000,1.000000,70.100000,324.200000,5.000000,1.000000,0.600000,6.430000,200.000000,41.00000,150.000000
max,20.000000,1.000000,94.700000,327.500000,5.900000,6.000000,3.700000,10.960000,450.000000,84.00000,410.000000

In [27]:
macro.describe()

              cpi  avg_hourly_earnings  real_wage_index
count   59.000000            60.000000        59.000000
mean   302.599576            33.855333        11.170308
std     17.550623             2.092746         0.130447
min    264.961000            30.030000        10.913500
25%    293.105500            32.167500        11.070200
50%    306.082000            33.950000        11.183700
75%    316.079500            35.622500        11.285950
max    327.460000            37.320000        11.396800

In [28]:
weather.describe()

       temp_mean_f   temp_max_f   temp_min_f
count  3655.000000  3655.000000  3655.000000
mean     59.075869    68.027196    51.732038
std      16.291083    18.072228    15.697015
min      -3.200000     5.500000    -9.300000
25%      48.900000    55.350000    42.400000
50%      61.200000    71.200000    53.200000
75%      71.600000    82.300000    62.800000
max      94.700000   114.200000    84.200000

### Count missing values in each dataset using isnull().sum()

In [29]:
menu.isnull().sum()

product_name      0
category          0
size              0
price_usd         0
calories          0
sugar_g           0
caffeine_mg      23
seasonal_flag     0
dtype: int64

In [30]:
transactions.isnull().sum()

transaction_id         0
date                   0
hour                   0
time_slot              0
city                   0
persona                0
is_weekend             0
temp_f                 0
cpi                 4324
category               0
product_name           0
size                   0
base_price             0
customizations         0
n_customizations       0
upcharge               0
total_price         4324
calories               0
sugar_g                0
caffeine_mg         8186
dtype: int64

In [31]:
macro.isnull().sum()

date                   0
cpi                    1
avg_hourly_earnings    0
real_wage_index        1
dtype: int64

In [32]:
weather.isnull().sum()

date           0
temp_mean_f    0
temp_max_f     0
temp_min_f     0
city           0
dtype: int64

### Check how many rows and columns each dataset has by using shape

In [37]:
menu.shape

(242, 8)

In [38]:
transactions.shape

(100000, 20)

In [39]:
macro.shape

(60, 4)

In [40]:
weather.shape

(3655, 5)

After checking those informations by using these expressions, no large issue is found within the four raw dataset.
Next will be data modeling, which helps define relationships between the four datasets (a preparation for merging them to one synthetic dataset) and points out issues that may determine how cleaning will be done.